 // File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4GG9wpJKfGcdkJPf6qYlM-g9tjWQr8lc',
    appId: '1:847889473023:web:202058255adc11ad6b5bca',
    messagingSenderId: '847889473023',
    projectId: 'digitalmandi-81a40',
    authDomain: 'digitalmandi-81a40.firebaseapp.com',
    storageBucket: 'digitalmandi-81a40.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6LBLuVGjxK32mrRjZQkFgDjApjcDL0EQ',
    appId: '1:847889473023:android:6c1353dbdb0a93a66b5bca',
    messagingSenderId: '847889473023',
    projectId: 'digitalmandi-81a40',
    storageBucket: 'digitalmandi-81a40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLm0jdAnVEX7f2LkDfQ3sEqwp31kv3g30',
    appId: '1:847889473023:ios:e64fbeeba05d311d6b5bca',
    messagingSenderId: '847889473023',
    projectId: 'digitalmandi-81a40',
    storageBucket: 'digitalmandi-81a40.appspot.com',
    iosClientId: '847889473023-d4qb314pbcve3v72m8ip5586eju4rv27.apps.googleusercontent.com',
    iosBundleId: 'com.example.digitalMandi',
  );
}
